### ISSUE TITLE
When can we start using jProtractor

### ISSUE THREAD

**Issue by kumarvarun1252** [caarlos0/jProtractor#1]
Hi,

We have a very sophisticated Selenium-WebDriver & Java Framework. We have some parts of the UI being implemented in AngularJS. We would like to use Protractor at the same time we want to leverage the existing WebDriver-Java framework.

Can you please let us know when will this be available to use?

Thanks,
Varun

**Comment by caarlos0** [comment]
Hi @kumarvarun1252 , so, I kind of stopped working with this right now because I have other priorities. Though, if you want to contribute, I'll help the best I can...
